name: CI

on: push

jobs:
  linting:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8
        run: |
          flake8 app.py